### ISSUE TITLE
Worker on another Node Not talking to ActiveMQ

### ISSUE THREAD

**Issue by BaddMann** [learnweb/docker-opencast#17]
I'm still mucking around with "Docker for Mac".
Just finally learned today that Docker Swarm doesn't work on "Docker for Mac" outside on external nodes! Well thats useless.

So tried to just use my other iMacs as workers. Now I'm stuck on the activeMQ not making a connection to the Docker instance on the master Node.

I wish I had more info, but I had to abandon this project as a class was going to use my make shift nodes. Any Advice on what to look for the next time I try this? How do I test that the ActiveMQ is responding on external ports? It's the only thing I think; "besides misconfigured settings"; that could be causing it to hang. I know nothing about ActiveMQ. Wish I could remove it's function to test the other stuff first.

**Comment by mtneug** [comment]
Without knowing how you started the ActiveMQ container, I assume you forgot to export the port to your host machine:

```yml
  activemq:
    image: webcenter/activemq:5.13.2
    environment:
      - ACTIVEMQ_MIN_MEMORY=128
      - ACTIVEMQ_MAX_MEMORY=1024
      - ACTIVEMQ_ENABLED_SCHEDULER=true
      - ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT=true
      - ACTIVEMQ_OWNER_LOGIN=admin
      - ACTIVEMQ_OWNER_PASSWORD=password
    ports:
      - "61616:61616"
    volumes:
      - ./assets/activemq.xml:/opt/activemq/conf/activemq.xml:ro
```

Note the new **ports** list. Also when starting your worker you must alter the address set in `ACTIVEMQ_BROKER_URL` to point to the correct machine.
